import * as XLSX from "xlsx";
import { SOURCES, SOURCE_LABEL, type Dataset } from "@/lib/types";
import { isLegacyGriSheet, parseLegacyGri, type LegacyMapping, type Rows } from "./legacyGri";
import {
  TEMPLATE_COLUMNS,
  TEMPLATE_INSTRUCTIONS,
  TEMPLATE_SHEET,
  isTemplate,
  parseTemplate,
  toTemplateRows,
  type TemplateRow,
} from "./template";
import { totalDischarge, totalWithdrawal } from "@/lib/metrics";

export type DetectedFormat = "legacy-gri" | "icmm-template";

export interface ImportResult {
  dataset: Dataset;
  format: DetectedFormat;
  sheetName: string;
}

export function readWorkbook(
  data: ArrayBuffer,
  fileName: string,
  opts: { mapping?: LegacyMapping; company?: string } = {},
): ImportResult {
  const wb = XLSX.read(data, { type: "array" });

  // 1. AquaTrace / ICMM template
  if (wb.SheetNames.includes(TEMPLATE_SHEET)) {
    const rows = XLSX.utils.sheet_to_json<TemplateRow>(wb.Sheets[TEMPLATE_SHEET], { defval: null });
    if (isTemplate(rows)) {
      return { dataset: parseTemplate(rows, fileName), format: "icmm-template", sheetName: TEMPLATE_SHEET };
    }
  }

  // 2. Legacy GRI 303 sheet anywhere in the workbook
  // Content-index sheets also mention "303-3", so try each candidate and keep
  // the first one that actually contains the withdrawal table.
  for (const name of wb.SheetNames) {
    const rows = XLSX.utils.sheet_to_json<Rows[number]>(wb.Sheets[name], { header: 1, defval: null, raw: true });
    if (!isLegacyGriSheet(rows)) continue;
    try {
      const dataset = parseLegacyGri(rows, {
        company: opts.company ?? guessCompany(fileName),
        sourceLabel: `${fileName}, sheet "${name}"`,
        mapping: opts.mapping,
      });
      if (dataset.sites.length) return { dataset, format: "legacy-gri", sheetName: name };
    } catch {
      // not the data sheet; keep looking
    }
  }

  throw new Error(
    `No water data found in "${fileName}". Upload either the AquaTrace template (sheet "${TEMPLATE_SHEET}") or a sustainability workbook with a GRI 303-3 water withdrawal table.`,
  );
}

function guessCompany(fileName: string) {
  const m = fileName.match(/(?:^|[_\s-])([A-Z][a-zA-Z]+)[_\s-]\d{4}/);
  return m ? m[1] : fileName.replace(/\.[a-z]+$/i, "");
}

function download(wb: XLSX.WorkBook, fileName: string) {
  XLSX.writeFile(wb, fileName, { compression: true });
}

/** Pre-filled template: the fastest way for a company to see what "complete" looks like. */
export function downloadTemplate(ds: Dataset | null) {
  const wb = XLSX.utils.book_new();
  const rows = ds ? toTemplateRows(ds) : [];
  const sheet = XLSX.utils.json_to_sheet(rows, { header: [...TEMPLATE_COLUMNS] });
  XLSX.utils.book_append_sheet(wb, sheet, TEMPLATE_SHEET);
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(TEMPLATE_INSTRUCTIONS), "instructions");
  download(wb, ds ? `aquatrace-template-${slug(ds.company)}-${ds.period}.xlsx` : "aquatrace-template-blank.xlsx");
}

/** ICMM 2021 Table 4 layout, aggregated for all sites and for water-stressed sites. */
export function downloadIcmmTable4(ds: Dataset) {
  const aoa: (string | number | null)[][] = [
    [`ICMM water reporting metrics, ${ds.company} ${ds.period}`],
    ["Generated by AquaTrace from", ds.sourceLabel],
    [],
    ["Scope", "Metric", "Source / destination", "High (ML)", "Low (ML)", "Total (ML)"],
  ];
  const scopes: [string, typeof ds.sites][] = [
    ["All sites", ds.sites],
    ["Sites in water-stressed areas", ds.sites.filter((s) => s.waterStress === "high" || s.waterStress === "extremely-high")],
  ];
  const sum = (xs: (number | null | undefined)[]) =>
    xs.some((x) => x === null || x === undefined) ? null : xs.reduce<number>((a, b) => a + (b ?? 0), 0);

  for (const [scope, sites] of scopes) {
    for (const metric of ["withdrawal", "discharge"] as const) {
      const label = metric === "withdrawal" ? "Operational water withdrawal" : "Total discharge";
      for (const src of SOURCES) {
        const high = sum(sites.map((s) => s[metric]?.[src].high));
        const low = sum(sites.map((s) => s[metric]?.[src].low));
        aoa.push([scope, label, SOURCE_LABEL[src], high, low, high === null || low === null ? null : high + low]);
      }
      const total = sum(sites.map((s) => (metric === "withdrawal" ? totalWithdrawal(s) : totalDischarge(s))));
      aoa.push([scope, label, "Total", null, null, total]);
    }
    aoa.push([scope, "Other managed water withdrawal", "", sum(sites.map((s) => s.omwWithdrawal?.high)), sum(sites.map((s) => s.omwWithdrawal?.low)), null]);
    aoa.push([scope, "Total consumption", "", null, null, sum(sites.map((s) => s.consumption))]);
    aoa.push([scope, "Operational water reuse/recycle", "", null, null, sum(sites.map((s) => s.reuse))]);
    aoa.push([scope, "Change in storage", "", null, null, sum(sites.map((s) => s.deltaStorage))]);
  }
  const stressed = scopes[1][1].length;
  aoa.push([]);
  aoa.push(["Water stress exposure", "Proportion of sites in water-stressed areas", "", `${stressed} of ${ds.sites.length} sites`, null, ds.sites.length ? Math.round((stressed / ds.sites.length) * 100) : null]);
  aoa.push([]);
  aoa.push(["Empty cells mean at least one site did not disclose the value. Stress levels flagged as 'assumed' must be replaced with a WRI Aqueduct assessment."]);

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(aoa), "ICMM Table 4");
  download(wb, `icmm-table4-${slug(ds.company)}-${ds.period}.xlsx`);
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
